imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*]

build:
  image: default-bionic

  nodes:
    my-tests:
      environment:
        php:
          version: 8.3.3
      tests:
        override:
          - command: composer install --no-interaction --prefer-dist --optimize-autoloader
          - command: composer phpunit
            coverage:
              file: "docs/coverage.clover"
              format: "php-clover"

    analysis:
      tests:
        override:
          - command: php-scrutinizer-run